### ISSUE TITLE
Job Accounts problems

### ISSUE THREAD

**Issue by TonybynMp4** [project-error/qb-pefcl#6]
- Doesn't update your status (contributor/admin) when changing grade
- changing **job** doesn't remove your access to the account

**Comment by SamShanks1** [comment]
@RoccoMyTacco

**Comment by ianvalls90** [comment]
Not even relog / restart server will remove access to  former job shared accounts. IE: you can access police account even you're not a police anymore

**Comment by mk3ext** [comment]
When changing job to another and back to the original job:

[        script:pefcl] [PEFCL] [accounts] [error]: User already exists in shared account.
[        script:pefcl] [PEFCL] [accounts] [error]: Failed to add user to unique account

Maybe the fix is remove access on job swap or compare with current grade?

**Comment by D40G** [comment]
can concur with the above issue, fresh qb-core build and only nwpd and pefcl on the build - removed qb-banking, qb-atm and qb-phone

![image](https://user-images.githubusercontent.com/10326968/192433872-56fe6ba2-32c4-4a8d-8afc-eb59352a7dc0.png)
![image](https://user-images.githubusercontent.com/10326968/192433946-222635c5-0e56-4980-884b-b4d500dc843b.png)

**Comment by RoccoMyTacco** [comment]
@mk3ext @ianvalls90 @TonybynMp4 Super late response but if yall haven't figured this out yourself you can give my branch a shot and see how it works https://github.com/RoccoMyTacco/qb-pefcl
